module.exports = {
    getActInfo: 'actId/info', //活动信息
    getActList: 'search', //活动列表
    addJoin: 'actId/join', //参与人数+1
    view: 'actId/view', //查看人数
    chkLogin: 'actId/chkLogin', //判断用户是否登录
    logout: 'actId/loginOut', //登出
    captcha: 'actId/captchaCode', //图形验证码（九宫格）
    sCaptchaCode: 'actId/sCaptchaCode', //图片验证码
    validateSCaptchaCode: 'actId/validateSCaptchaCode', //验证图形验证码
    smsCaptchaCode: 'actId/smsCaptchaCode', //短信验证码
    sweeper: 'actId/sweeper', //判断内容是否有敏感词
    getServerTime: 'time', //获取服务器时间
    getField: 'actId/form', //获取表单项
    saveForm: 'actId/form/fieldSetId/saveData', //保存表单
    vote: 'actId/form/fieldSetId/vote', //投票
    dataList: 'actId/form/fieldSetId/dataList', //展示信息列表(针对设置信息收集模块为【展示】）
    getInfo: 'actId/form/fieldSetId/info', //根据登录用户ID/或收集信息ID得到其收集信息
    getTotalScore: 'actId/form/fieldSetId/totalScore', //根据展示收集得到总评分及总数
    getTotalCount: 'actId/form/fieldSetId/totalCount', //根据展示/收集得到总数
    getLotteryJoinCount: 'actId/log/lotteryId/join', //获取参与抽奖人数
    getLotteryWinnerCount: 'actId/log/lotteryId/winnerCount', //获取抽奖中奖人数
    getLotteryJoinInfo: 'actId/log/lotteryId/info', //根据条件查询抽奖数据
    getLotteryWinnerInfo: 'actId/log/lotteryId/winner', //根据条件查询抽奖中奖数据
    redeemPrize: 'actId/log/lotteryId/winnerReceive', //兑现奖品
    getWinnerList: 'actId/log/lotteryId', //查询中奖列表
    myActLog: 'http://p.act.17173.com/api/v2/log/myActList', //我的参与活动纪录
    getTypeWinnerList: 'http://p.act.17173.com/api/v2/log/winnerList', //得到指定分类下的最新中奖信息列表（用于页游活动平台）
    doLottery: 'actId/lottery/lotteryId', //抽奖
    getLotteryInfo: 'actId/lottery/lotteryId/info', //获取抽奖信息
    bindGameUser: 'actId/lottery/lotteryId/bindGame', //第三方接口绑定用户游戏信息
    getBindUserInfo: 'actId/lottery/lotteryId/getBind', //查询登录用户是否已绑定
    registerGirl: 'actId/lady/register', //注册女神
    uploadGirlPicture: 'actId/lady/upload', //上传女神图片
    getGirlInfo: 'actId/lady/info', //获取女神信息
    getGirlPictures: 'actId/lady/pics', //获取女神图片
    setGirlCover: 'actId/lady/setcover', //设置指定照片为女神封面
    deleteGirlPicture: 'actId/lady/delete', //删除指定女神图片
    voteGirl: 'actId/lady/vote', //给女神投票
    searchGirl: 'actId/lady/search', //搜索女神
    uploadPicture: 'actId/picture/upload', //上传图片
    getPicturesList: 'actId/picture/pics', //图片列表
    getPicture: 'actId/picture/show', //获取指定图片
    votePicture: 'actId/picture/vote', //给图片投票
    composePictures: 'actId/picture/compose', //合成图片
    deletePicture: 'actId/picture/delete', //删除指定图片
    getQuestionsList: 'actId/question/getList', //获取问答列表
    saveQuestionAnswer: 'actId/question/answer', //提交答案
    sendSms: 'actId/sms/smsId/send', //下发短信
    chkSmsToken: 'actId/sms/smsId/chkToken', //验证短信模块令牌串
    sendEmail: 'actId/email/emailId/send', //发送邮件
    sign: 'actId/sign/signId', //签到（针对登陆或IP用户） 
    getSignInfo: 'actId/sign/signId/list' //查询用户签到纪录
};